<?php

namespace PruebasBundle\Repository;

/**
 * ffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ffRepository extends \Doctrine\ORM\EntityRepository
{
}
