otra_prueba:
    resource: "@OtraPruebaBundle/Controller/"
    type:     annotation
    prefix:   /

pruebas:
    resource: "@PruebasBundle/Resources/config/routing.yml"
    prefix:   /prueba

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
