PruebasBundle\Entity\Event:
    type: entity
    table: event
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nameEvent:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
            column: name_event
        date:
            type: datetime
            nullable: false
        city:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        population:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
